import 'dart:ui';
final primaryColor = Color(0xff203152);
final white = Color(0x99ffffff);
final teal = Color(0xffe0f2f1);
final teal400 = Color(0xff26a69a);
final blurRad = 5.0;
final cyan = Color(0xff006064);
final blueGrey = Color(0xff263238);
final appName = "TalkApp";
final defaultRoom = 'DEF';
final List<String> defaultRoles = <String> ['','Sanitario', 'Docente', 'Familia'];